server:
  port: 8080
  error:
    include:
      message: true

spring:
  application:
    name: rococo-gateway

rococo-userdata.client: rest


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    net.devh.boot.grpc: DEBUG
  #    org.springframework.boot.autoconfigure: DEBUG

  file:
    name: 'gateway.log'


---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

rococo-userdata:
  base-uri: 'http://127.0.0.1:8089'
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'

rococo-userdata:
  base-uri: 'http://userdata.rococo.dc:8089'
rococo-front:
  base-uri: 'http://frontend.rococo.dc'
---
spring:
  config:
    activate:
      on-profile: 'prod'
    import: vault://
  cloud:
    vault:
      authentication: TOKEN
      host: vault.qa.guru
      port: 443
      scheme: https
      uri: https://vault.qa.guru:443
      token: ${VAULT_TOKEN}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.rococo.qa.guru'

rococo-userdata:
  base-uri: ${rococo-userdata.url}
rococo-front:
  base-uri: 'https://rococo.qa.guru'
---
spring:
  config:
    activate:
      on-profile: 'staging'
    import: vault://
  cloud:
    vault:
      authentication: TOKEN
      host: vault.qa.guru
      port: 443
      scheme: https
      uri: https://vault.qa.guru:443
      token: ${VAULT_TOKEN}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.rococo-stage.qa.guru'

rococo-userdata:
  base-uri: ${rococo-userdata.url}
rococo-front:
  base-uri: 'https://rococo-stage.qa.guru'
---